# Generated by Django 2.0.3 on 2018-04-04 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='イベント名')),
                ('description', models.TextField(verbose_name='イベント概略')),
                ('readme', models.TextField(verbose_name='説明')),
                ('published_date', models.DateTimeField(null=True, verbose_name='公開日')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='イベント作成ユーザ')),
            ],
        ),
        migrations.CreateModel(
            name='EventJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Event', verbose_name='イベント')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='EventSkillTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=16, verbose_name='技術タグ')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Event', verbose_name='イベント')),
            ],
        ),
    ]
